apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-nginx
data:
  nginx.conf: |
    user  nginx;
    worker_processes  auto;
    worker_rlimit_nofile  30000;
    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;

    events {
        worker_connections  8000;
    }
    
    http {
        default_type  application/octet-stream;
        include       /etc/nginx/mime.types;
        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';
        access_log  /var/log/nginx/access.log  main;
        sendfile        on;
        #tcp_nopush     on;
        keepalive_timeout  65;
        gzip  on;
        include /etc/nginx/conf.d/*.conf;
        #server_tokens off;

        server {
          root /usr/share/nginx/html;
          index index.html;
          listen 8000;
          server_name _;

          location = /favicon.ico {
            return 204;
          }
        }
    }
