# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Frontend CI

on:
  push:
    paths:
      - 'frontend/**'
      - '!backend/**'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install
      working-directory: ./frontend
      run: yarn install
    - name: check
      run: yarn pretty:check
      working-directory: ./frontend
    - name: Test
      run: yarn test
      working-directory: ./frontend
    - name: Build
      working-directory: ./frontend
      run: yarn build
    - name: Build and Push template image
      uses: docker/build-push-action@v1 # https://github.com/docker/build-push-action
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        path: ./frontend/
        dockerfile: ./frontend/Dockerfile
        repository: parity/substrate-telemetry-frontend
        push: ${{ startsWith(github.ref, 'refs/tags/') }}
        tags: latest
        add_git_labels: true
